---- Enums
  CREATE TYPE user_role AS ENUM('client','escort','consultant','admin');
  CREATE TYPE user_status AS ENUM('active','inactive','suspended','verified');
  CREATE TYPE subscription_tiers AS ENUM('free','basic','premium','elite');
  CREATE TYPE media_group AS ENUM('card_photos', 'card_videos', 'card_audios', 'gallery_photos', 'gallery_videos', 'gallery_audios');
  CREATE TYPE transaction_type AS ENUM('deposit', 'withdrawal', 'payment', 'refund');
  CREATE TYPE transaction_method AS ENUM('pix', 'card', 'crypto', 'giftcard', 'wallet');
  CREATE TYPE transaction_status AS ENUM('pending', 'completed', 'failed', 'cancelled');
  CREATE TYPE review_status AS ENUM('pending','approved','rejected');
  CREATE TYPE booking_status AS ENUM('requested','confirmed','completed','cancelled');
  CREATE TYPE message_type AS ENUM('text','image','audio','video');
  CREATE TYPE message_status AS ENUM('sent','delivered','read');
  CREATE TYPE story_type AS ENUM('image','video');
  CREATE TYPE report_status AS ENUM('open','reviewing','closed');
  CREATE TYPE source_type AS ENUM('boost', 'subscription');
  CREATE TYPE verification_status AS ENUM('requested', 'approved', 'rejection');

---- Profiles 
  CREATE TABLE public.profiles (
    id uuid not null,
    full_name text not null,
    cpf text not null,
    birth_date date null,
    phone text not null,
    role public.user_role null default 'client'::user_role,
    status public.user_status null default 'active'::user_status,
    avatar_url text null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    age integer null,
    gender character varying null,
    on_boarded boolean null default false,
    biography text null,
    escort_details text null,
    rating real not null default '0'::real
  );

  CREATE INDEX idx_profiles_role ON profiles(role);
  CREATE INDEX idx_profiles_cpf ON profiles(cpf);

---- Clients
  create table public.clients (
    id uuid not null,
    preferences jsonb not null default '{}'::jsonb,
    location jsonb null default '{}'::jsonb,
    geo_location geography null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint clients_pkey primary key (id),
    constraint clients_id_fkey foreign KEY (id) references profiles (id) on delete CASCADE
  );
  
  CREATE INDEX IF NOT EXISTS idx_clients_geo_location ON clients USING GIST (geo_location);

---- Escorts
  create table public.escorts (
    id uuid not null,
    stage_name character varying(100) null,
    physical_attributes jsonb not null default '{}'::jsonb,
    services_offered jsonb not null default '[]'::jsonb,
    pricing jsonb not null default '{}'::jsonb,
    availability jsonb not null default '[]'::jsonb,
    languages text[] null default array[]::text[],
    location jsonb null default jsonb_build_object('city', '', 'state', '', 'country', ''),
    geo_location geography null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    public_number bigint generated by default as identity not null,
    public_slug text null,
    constraint escorts_pkey primary key (id),
    constraint escorts_id_fkey foreign KEY (id) references profiles (id) on delete CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_escorts_geo_location ON escorts USING GIST (geo_location);

---- Consultants
  CREATE TABLE consultants (
    id uuid PRIMARY KEY REFERENCES profiles (id) ON DELETE CASCADE,
    address TEXT,
    operating_region VARCHAR(100),
    commission NUMERIC(7,4),
    sales_target NUMERIC(12,2),
    sales_history JSONB DEFAULT '{}'::jsonb,
    referral_links TEXT[] DEFAULT ARRAY[]::TEXT[],
    conversion_statistics JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

--- Escort Boosts
  CREATE TABLE escort_boosts (
    id uuid not null default gen_random_uuid (),
    escort_id uuid not null,
    boost_name text null,
    package_label text null,
    expires_at timestamp with time zone not null,
    next_activation_at timestamp with time zone not null,
    remaining_minutes timestamp with time zone null,
    auto_renew boolean null,
    created_at timestamp with time zone null default now(),
    constraint escort_boosts_pkey primary key (id),
    constraint escort_boosts_escort_id_fkey foreign KEY (escort_id) references escorts (id)
  );

--- Escort Media
  create table public.escort_media (
    id uuid not null default gen_random_uuid (),
    escort_id uuid not null,
    storage_path text not null,
    public_url text not null,
    thumb_url text not null,
    media_group public.media_group not null,
    type text not null,
    created_at timestamp with time zone not null default now(),
    duration_seconds bigint null,
    updated_at timestamp with time zone null,
    deleted_at timestamp with time zone null,
    metadata jsonb null default '{}'::jsonb,
    sort_order integer null default 0,
    visibility public.media_visibility not null default 'public'::media_visibility,
    constraint escort_media_pkey primary key (id),
    constraint unique_user_sort_order unique (escort_id, sort_order),
    constraint escort_media_escort_id_fkey foreign KEY (escort_id) references escorts (id) on update CASCADE on delete CASCADE
  );

  CREATE INDEX idx_escort_medias ON escort_media(escort_id);
  CREATE INDEX idx_media_group ON escort_media(media_group);

---- Wallets
  create table public.wallets (
    id uuid not null default gen_random_uuid (),
    profile_id uuid not null,
    balance numeric(12, 2) not null default 0.00,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint wallets_pkey primary key (id),
    constraint wallets_profile_id_key unique (profile_id),
    constraint wallets_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete CASCADE
  );

  CREATE INDEX idx_wallets_profile_id ON wallets(profile_id);

---- Transactions
  create table public.transactions (
    id uuid not null default gen_random_uuid (),
    wallet_id uuid not null,
    type public.transaction_type not null,
    method public.transaction_method null,
    amount numeric(12, 2) not null,
    status public.transaction_status null default 'pending'::transaction_status,
    external_reference text null,
    description text null,
    metadata jsonb null default '{}'::jsonb,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint transactions_pkey primary key (id),
    constraint transactions_wallet_id_fkey foreign KEY (wallet_id) references wallets (id) on delete CASCADE
  );

  CREATE INDEX idx_transactions_wallet_id ON transactions(wallet_id);
  CREATE INDEX idx_transactions_status ON transactions(status);

---- Subscriptions
  create table public.subscriptions (
    id uuid not null default gen_random_uuid (),
    profile_id uuid not null,
    profile_type public.user_role not null,
    tier public.subscription_tiers not null,
    price numeric not null,
    status public.subscription_status not null default 'pending'::subscription_status,
    started_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone null,
    metadata jsonb null default '{}'::jsonb,
    transaction_id uuid null,
    preapproval_id text null,
    external_reference text null,
    constraint subscriptions_pkey primary key (id),
    constraint subscriptions_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete CASCADE,
    constraint subscriptions_transaction_id_fkey foreign KEY (transaction_id) references transactions (id)
  ) TABLESPACE pg_default;

---- Reviews
  CREATE TABLE reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reviewer_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    reviewed_id UUID NOT NULL REFERENCES escorts(id) ON DELETE CASCADE,
    rating SMALLINT CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status review_status DEFAULT 'pending'
  );

  create index idx_reviews_escort_id on public.reviews(reviewed_id);
  create index idx_reviews_client_id on public.reviews(reviewer_id);

---- Chats
  CREATE TABLE chats (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subject TEXT,
    is_group BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

---- Chat Participants
  CREATE TABLE chat_participants (
    chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    role TEXT,
    PRIMARY KEY (chat_id, profile_id)
  );

---- Messages
  CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT,
    message_type message_type DEFAULT 'text',
    status message_status DEFAULT 'sent',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX idx_messages_chat_id_created_at ON messages(chat_id, created_at DESC);

---- Stories
  create table public.stories (
    id uuid not null default gen_random_uuid (),
    escort_id uuid not null,
    items jsonb null default '[]'::jsonb,
    story_url text not null,
    story_type public.story_type not null,
    created_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone null default (now() + '24:00:00'::interval),
    views bigint null default 0,
    constraint stories_pkey primary key (id),
    constraint stories_escort_id_fkey foreign KEY (escort_id) references escorts (id) on delete CASCADE
  );

  CREATE INDEX idx_stories_escort_id ON stories(escort_id);

---- Reports
  CREATE TABLE reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reporter_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    reported_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    report_type VARCHAR(100),
    description TEXT,
    evidence TEXT[] DEFAULT ARRAY[]::TEXT[],
    status report_status DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX idx_reports_reported_id ON reports(reported_id);

---- Contact Verifications
  CREATE TABLE public.contact_verifications (
    contact_type text NOT NULL,
    contact_value text NOT NULL,
    code_hash text NOT NULL,
    attempts_remaining integer NOT NULL DEFAULT 5,
    expires_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT contact_verifications_pkey PRIMARY KEY (contact_type, contact_value)
  );
  CREATE INDEX contact_verifications_status_idx ON public.contact_verifications USING btree (contact_type, contact_value, verified_at);

--- Platform Earning
  CREATE TABLE public.platform_earnings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_type public.source_type not null,
    source_id UUID NOT NULL, --- Either link to a escort_boots row or escort_subscriptions row
    profile_id UUID NOT NULL references public.profiles (id) on delete cascade,
    tier public.subscription_tier,
    package_label text,
    amount numeric(12,2) not null,
    currency text not null,
    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX idx_platform_earnings_profile_id ON public.platform_earnings(profile_id);
  CREATE INDEX idx_platform_earnings_source_id ON public.platform_earnings(source_id);

---- JOIN TABLES
  ---- Consultant -> Escorts 1:N
    CREATE TABLE consultant_escorts (
      consultant_id UUID NOT NULL REFERENCES consultants(id) ON DELETE CASCADE,
      escort_id UUID NOT NULL REFERENCES escorts(id) ON DELETE CASCADE,
      assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      PRIMARY KEY (consultant_id, escort_id)
    );

  ---- Client -> Escorts 1:N
    CREATE TABLE client_favorites (
      client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
      escort_id UUID NOT NULL REFERENCES escorts(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      PRIMARY KEY (client_id, escort_id)
    );

---- Logs and Audit tables
  ---- User Activity Logs
    create table public.user_activity_logs (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      table_name text NOT NULL,
      record_id uuid,
      action text NOT NULL,
      old_data jsonb,
      new_data jsonb,
      changed_by uuid,
      created_at timestamp with time zone DEFAULT now(),
    ); 
    create index idx_user_activity_profile_id on public.user_activity_logs(profile_id);
    create index idx_user_activity_logs_created_at on public.user_activity_logs(created_at);

  ---- Audit Logs
    CREATE TABLE public.audit_logs (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      table_name text NOT NULL,
      record_id uuid,
      action text NOT NULL,
      old_data jsonb,
      new_data jsonb,
      changed_by uuid,
      created_at timestamp with time zone DEFAULT now(),
      CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
      CONSTRAINT data_audit_performed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id)
    ); 
    create index idx_data_audit_table_name on public.audit_logs(table_name);

    -- Track all user visits to escort profiles
    create table public.escort_profile_views (
      id uuid primary key default gen_random_uuid(),
      escort_id uuid not null references public.escorts(id) on delete cascade,
      viewer_id uuid references public.clients(id),
      created_at timestamptz not null default now()
    );
    
    -- Optional: aggregate table for faster analytics
    create table public.escort_metrics_daily (
      escort_id uuid not null references public.escorts(id) on delete cascade,
      date date not null,
      views int default 0,
      favorites int default 0,
      primary key (escort_id, date)
    );
